record: Use mpv instead of vlc

diff --git a/record b/record
--- a/record
+++ b/record
@@ -1,22 +1,20 @@
-#!/usr/bin/bash
+#!/usr/bin/zsh
 
-CHANNEL="${HOME}/Videos/TV/Channels/$(basename ${1-NULL} .xspf).xspf"
-DURATION=${2-60}
-PID=-1
+program=${0}
+channel=${1}
+typeset -i duration=${2}
 
-if [ ! -f ${CHANNEL} ]; then
-	echo 'Channel not found'
+if (( duration <= 0 )); then
+	echo "Invalid duration '${2}'" >&2
+	echo "Usage: ${program:t} CHANNEL MINUTES" >&2
 	exit 1
 fi
 
-OUTFILE="${HOME}/Videos/TV/Recorded/$(basename ${CHANNEL} .xspf)-$(date -I).mpg"
-nohup cvlc "${CHANNEL}" --sout "${OUTFILE}" &> /dev/null &
-PID=${!}
+shift
+outfile="${HOME}/Videos/TV/Recorded/${channel}_$(date -I).mpg"
+mpv "dvb://${channel}" "${@}" --vo=opengl --stream-dump="${outfile}" &!
+pid=${!}
 
-at NOW + ${DURATION} MINUTE << HERE
-	if [ ${PID} != -1 ]; then
-		kill ${PID}
-	else
-		pkill vlc
-	fi
+at now + "${duration}" minutes << HERE
+	kill ${pid}
 HERE
